# Vamos a encontrar los coeficientes de expansión

In [2]:
import numpy as np



In [4]:
# Ponemos la forma del hamiltonaino que tenemos

# Los valores que ellos utilizan

# wc = 1.25
# wa = 1.0
# g = 0.05

wc = 1
wa = 1
g = 0.5
J=3/2

l=np.array([[3-J, g*(6*J)**(1/2),0,0],[g*(6*J)**(1/2),2-(J-1),2*g*(2*J-1)**(1/2),0],[0,2*g*(2*J-1)**(1/2), 1-(J-2) ,g*(6*(J-1))**(1/2)],[0,0,g*(6*(J-1))**(1/2), -(J-3)]])

print(l)

[[1.5        1.5        0.         0.        ]
 [1.5        1.5        1.41421356 0.        ]
 [0.         1.41421356 1.5        0.8660254 ]
 [0.         0.         0.8660254  1.5       ]]


In [5]:
import numpy as np

# Definir una matriz (por ejemplo)
# matriz = np.array([[1, 2], [2, 4]])

# Encontrar los autovalores y autofunciones
autovalores, autofunciones = np.linalg.eig(l)

# Mostrar los autovalores y autofunciones
print("Autovalores:")
print(autovalores)
print("\nAutofunciones:")
print(autofunciones)

Autovalores:
[-0.65313746  3.65313746  0.89667665  2.10332335]

Autofunciones:
[[ 0.46982945  0.46982945  0.52845084 -0.52845084]
 [-0.67440493  0.67440493 -0.21255115 -0.21255115]
 [ 0.52845084  0.52845084 -0.46982945  0.46982945]
 [-0.21255115  0.21255115  0.67440493  0.67440493]]


# Esto me dio unos autovalores y unas autofunciones diferentes que la resolución con 'calculadora de matrices' :C

In [13]:
import sympy as sp

# Definir una matriz (como símbolos)
# a, b, c, d = sp.symbols('a b c d')
matriz_sympy = sp.Matrix(l)

# Calcular autovalores y autovectores
autovalores_sympy = matriz_sympy.eigenvals()
autovectores_sympy = matriz_sympy.eigenvects()

# Mostrar los resultados
print("Autovalores (SymPy):")
print(autovalores_sympy)
print("\nAutovectores (SymPy):")
print(autovectores_sympy)

Autovalores (SymPy):
{-0.653137463407616: 1, 3.65313746340762: 1, 0.896676650815985: 1, 2.10332334918402: 1}

Autovectores (SymPy):
[(-0.653137463407616, 1, [Matrix([
[  0.46982945118518],
[-0.674404928506034],
[ 0.528450836690635],
[-0.212551152447526]])]), (3.65313746340762, 1, [Matrix([
[ -0.46982945118518],
[-0.674404928506034],
[-0.528450836690635],
[-0.212551152447526]])]), (0.896676650815985, 1, [Matrix([
[ 0.528450836690635],
[-0.212551152447526],
[ -0.46982945118518],
[ 0.674404928506034]])]), (2.10332334918402, 1, [Matrix([
[-0.528450836690635],
[-0.212551152447526],
[  0.46982945118518],
[ 0.674404928506034]])])]


# Entocontrar los coheficientes

In [65]:
import sympy
from sympy import symbols, I, exp, simplify

a=symbols('a')
b=symbols('b')
c=symbols('c')
d=symbols('d')

t=symbols('t')

e1=sp.exp(-0.65313746*I*t)
e2=sp.exp(3.65313746*I*t)
e3=sp.exp(0.89667665*I*t)
e4=sp.exp(2.10332335*I*t)

In [ ]:
# Autovalores:
# [-0.65313746  3.65313746  0.89667665  2.10332335]

# Autofunciones:
# [[ 0.46982945  0.46982945  0.52845084 -0.52845084]
#  [-0.67440493  0.67440493 -0.21255115 -0.21255115]
#  [ 0.52845084  0.52845084 -0.46982945  0.46982945]
#  [-0.21255115  0.21255115  0.67440493  0.67440493]]

In [66]:
c1=a*0.46982945*e1+b*0.46982945*e2+c*0.52845084*e3-d*0.52845084*e4

c2=-a*0.67440493*e1+b*0.67440493*e2-c*0.21255115*e3-d*0.21255115*e4

c3=a*0.52845084*e1+b*0.52845084*e2 -c*0.46982945*e3+d*0.46982945*e4

c4=-a*0.21255115*e1+b*0.21255115*e2+c*0.67440493*e3+d*0.67440493*e4


Aplicando condiciones iniciales, se pueden hallar a, b, c y d



In [68]:
import sympy as sp

# Definir vwriwbles simbólicws
w, x, y, z = sp.symbols('w x y z')

# Definir lws ecuwciones

y1=w*0.46982945*1+x*0.46982945*1+y*0.52845084*1-z*0.52845084*1-((2)**(1/2))/3

y2=-w*0.67440493*1+x*0.67440493*1-y*0.21255115*1-z*0.21255115*1+0

y3=w*0.52845084*1+x*0.52845084*1 -y*0.46982945*1+z*0.46982945*1+0

y4=-w*0.21255115*1+x*0.21255115*1+y*0.67440493*1+z*0.67440493*1-((7)**(1/2))/3

# Resolver el sistemw de ecuwciones
solucion = sp.solve((y1,y2,y3,y4), (w,x, y,z))

print("Lw solución es:", solucion)

Lw solución es: {w: 0.0340272314465424, x: 0.408932219902948, y: 0.843883355223323, z: 0.345655127615246}


# Valores de a, b,c y d

In [69]:
a=0.0340272314465424
b=0.408932219902948
c=0.843883355223323
d=0.345655127615246

## Valores de los números

In [76]:
c1=a*0.46982945*e1+b*0.46982945*e2+c*0.52845084*e3-d*0.52845084*e4
c2=-a*0.67440493*e1+b*0.67440493*e2-c*0.21255115*e3-d*0.21255115*e4
c3=a*0.52845084*e1+b*0.52845084*e2 -c*0.46982945*e3+d*0.46982945*e4
c4=-a*0.21255115*e1+b*0.21255115*e2+c*0.67440493*e3+d*0.67440493*e4

c1c=sp.conjugate(c1)
c2c=sp.conjugate(c2)
c3c=sp.conjugate(c3)
c4c=sp.conjugate(c4)

In [75]:
print(c1)
print(60*'***')
print(c1c)

0.445950867929783*exp(0.89667665*I*t) - 0.182661742538584*exp(2.10332335*I*t) + 0.192128399964281*exp(3.65313746*I*t) + 0.0159869954355517*exp(-0.65313746*I*t)
************************************************************************************************************************************************************************************
0.0159869954355517*exp(0.65313746*I*conjugate(t)) + 0.192128399964281*exp(-3.65313746*I*conjugate(t)) - 0.182661742538584*exp(-2.10332335*I*conjugate(t)) + 0.445950867929783*exp(-0.89667665*I*conjugate(t))


In [77]:
def generar_matriz_multiplicacion(lista1, lista2):
    if len(lista1) < 4 or len(lista2) < 4:
        raise ValueError("Ambas listas deben contener al menos 4 elementos.")

    matriz = [[0 for _ in range(4)] for _ in range(4)]

    for i in range(4):
        for j in range(4):
            num1 = lista1[i]  # Tomamos el número de la primera lista según el índice i
            num2 = lista2[j]  # Tomamos el número de la segunda lista según el índice j
            resultado = num1 * num2  # Multiplicamos los dos números

            matriz[i][j] = resultado

    return matriz

# Listas con al menos 4 elementos cada una
lista_1 = [c1, c2, c3, c4]
lista_2 = [c1c, c2c, c3c, c4c]

# Generar la matriz de 4x4 con términos resultado de multiplicaciones entre elementos de las listas
matriz_resultado = generar_matriz_multiplicacion(lista_1, lista_2)

# Imprimir la matriz generada
print("Matriz de densidad es: ")
for fila in matriz_resultado:
    print(fila)

Matriz de densidad es: 
[(0.445950867929783*exp(0.89667665*I*t) - 0.182661742538584*exp(2.10332335*I*t) + 0.192128399964281*exp(3.65313746*I*t) + 0.0159869954355517*exp(-0.65313746*I*t))*(0.0159869954355517*exp(0.65313746*I*conjugate(t)) + 0.192128399964281*exp(-3.65313746*I*conjugate(t)) - 0.182661742538584*exp(-2.10332335*I*conjugate(t)) + 0.445950867929783*exp(-0.89667665*I*conjugate(t))), (0.445950867929783*exp(0.89667665*I*t) - 0.182661742538584*exp(2.10332335*I*t) + 0.192128399964281*exp(3.65313746*I*t) + 0.0159869954355517*exp(-0.65313746*I*t))*(-0.0229481326417992*exp(0.65313746*I*conjugate(t)) + 0.275785905138392*exp(-3.65313746*I*conjugate(t)) - 0.0734693948780173*exp(-2.10332335*I*conjugate(t)) - 0.179368377618576*exp(-0.89667665*I*conjugate(t))), (0.445950867929783*exp(0.89667665*I*t) - 0.182661742538584*exp(2.10332335*I*t) + 0.192128399964281*exp(3.65313746*I*t) + 0.0159869954355517*exp(-0.65313746*I*t))*(0.0179817190407997*exp(0.65313746*I*conjugate(t)) + 0.21610057511077