# Calculos base en qutip

## Para esta librería se requiere instalar:

In [1]:
'Con esto es sificiente para llamar a todos los módulos de la libreria'
from qutip import *

import qutip as qt

import numpy as np

import matplotlib.pyplot as plt

## Creación de vectores

In [2]:
'Forma de crear un ket'
print(Qobj([[1],[2],[3],[4],[5]]))

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [3]:
'Forma de crear un bra'
x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


# Estados en la base de Fock

[Fock state ket vector](https://qutip.org/docs/latest/guide/guide-basics.html)



In [4]:
#Estado de vacío:
p0=fock(4,0)
#print(p0)
p0

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

¿Cómo se crea un estado exitado?

Pues, se debe aplicar el operador de creación $a^{\dagger}$. Pero antes de ello, se crea el de destruccón, ya que el de creación corresponde al hermítico conjugado.


In [5]:
'Operador de destrucción, para 4 posibles estados'
# Notemos que a excepción de la primera columna, este operador corresponde a una
#matriz diagonal, donde cada elemento d ela diagonal es la raiz cuadrada de cada
#número posible de partículas.

a = destroy(4)
a

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [6]:
#Notemos que aplicar el operador destrucción al estado de vacío, retorna 
#el vector nulo.
a*p0

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]]

In [7]:
'Entonces, como se dijo, el operador creación corresponde al adjunto del aniquilación:'

aplus=a.dag()
aplus

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [8]:
'Operador creación'
#También se pudo haber hecho:
c=create(4)
c

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [9]:
#Primer estado exitado |1>
p1=aplus*p0
p1

p11=c*p0
p11

#Eliga cual eliga, corresponde a lo mismo.

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [10]:
#Con esta operación estoy haciendo: $a+|1>=(2)**1/2 |2>$
(c**2*p0)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]]

## Estados de Fock posibles para mi caso




In [11]:
#Estado de vacío |0>:
p0=fock(4,0)
p0

#primer estado excitado |1>:
p1=fock(4,1)
p1

#segundo estado excitado |2>:
p2=fock(4,2)
p2

#tercero estado excitado |3>:
p3=fock(4,3)
p3

#Notemos que los vectores escritos de esta manera están normalizados para
#el valor de 1

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [12]:
'operador número: creación*destrucción=n'
n=num(4)
n

n*p3

#Lo que corresponde a 3|3>

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [3.]]

## Base de Dicke

Los vectores de esta base, tienen la forma:
|-J>, |-J+1>, |-J+2>, |-J+3>.
Donde recordemos que realmente se tiene es:
|M>, y como M puede tomar valores: +-J,+-J-+1...


Y deben ser opuestos a la forma de los de Fock, ya que, de forma compuesta, la base corresponde a:
|-J,3>, |-J+1,2>, |-J+2,1>, |-J+3,0>.

In [13]:
#Estados de Dicke

#Estado base |-J> 
d0=basis(4,0)
d0

#Estado base |-J+1> 
d1=basis(4,1)
d1

#Estado base |-J+2> 
d2=basis(4,2)
d2

#Estado base |-J+3> 
d3=basis(4,3)
d3

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [14]:
#producto tensorial entre estos elementos:

#|-J,3>
d0p3=tensor([d0, p3])
d0p3

# |-J+1,2>
d1p2=tensor([d1, p2])
d1p2

# |-J+2,1>
d2p1=tensor([d2, p1])
d2p1

# |-J+3,0>
d3p0=tensor([d3, p0])
d3p0

Quantum object: dims = [[4, 4], [1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]

## A solucionar: ¿qué hago con el - J que tengo faltante en la base de Dicke?

Pero lo cierto es que ese valor de -J es importante para cuando se aplique los operadores J's.

Bueno, resulta que esa no era la manera de formar la base de Dicke. La manera es la siguiente:

In [15]:
#Valor de número total de espin
j = 3/2
#Base de Dicke para los emisores. Como m puede tomar valores entre -j hasta j.
#se tienen jj+1 posibles combinaciones.
jj=int(2*j)

di = qt.basis(jj + 1,jj-1)
di

#Creo que ya entendí esto:
#El producto vectorial entre los vectores de las bases de fock y de dicke, se da entre opuestos
#es decir, mientras que los cuantos surgen, son menores las exitaciones por parte
#de los emisores.
#Y que sea -J con el mayor número de fotones (no es un valor, sino un íncide. (M=-j))
#denotando que es el menor número de exitaciones de los emisores.


#Como este es el último término, corresponde al estado con menor exitación posible, M=-J
di3=qt.basis(jj + 1,jj)
di3

di2=qt.basis(jj + 1,jj-1)
di2

di1=qt.basis(jj + 1,jj-2)
di1

#Este es el estado con mayor exitación posible, M=-J+3
di0=qt.basis(jj + 1,jj-3)
di0

di0

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

## Producto tensorial para nuestro problema

In [16]:
#producto tensorial entre estos elementos:

#|-J,3>
di3p3=tensor([di3, p3])
di3p3

# |-J+1,2>
di2p2=tensor([di2, p2])
di2p2

# |-J+2,1>
di1p1=tensor([di1, p1])
di1p1

# |-J+3,0>
di0p0=tensor([di0, p0])
di0p0


Quantum object: dims = [[4, 4], [1, 1]], shape = (16, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

## Operador que va  acorresponder a la base de Dicke

In [17]:
jmat(j,'+')*di3

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.73205081]
 [0.        ]]

![](fotoo.jpeg)

Esta documentaci´+on se encuentra en el siguiente enlace:

https://qutip.org/docs/latest/apidoc/functions.html#qutip.operators.jmat

## Hallando la forma del hamiltoniano con estos vectores base

In [18]:
N=4
j=3/2
m=-j
wc=1
wa=1
g=0.5

a=destroy(N)
a.dag()

jz=jmat(j,'z')

jmin=jmat(j,'-')

jmax=jmat(j,'+')

In [19]:
#Supuestamente, este es el hamiltoniano mio 
htc=wc*a.dag()*a + wa*jz + g*(a.dag()*jmin + a*jmax)

htc

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[1.5        0.         1.         0.        ]
 [0.         1.5        0.         1.22474487]
 [1.22474487 0.         1.5        0.        ]
 [0.         1.73205081 0.         1.5       ]]

In [20]:
wc*a.dag()*a

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]

El 'suúestamente' surge por la dimensionalidad de los operadores y de los vectores. no son compatibles

In [21]:
htc*di2p2

TypeError: Incompatible Qobj shapes

Como dice que los shapes no son compatibles, supongo que la matriz del hamiltoniano debería quedar 16x16

In [ ]:
a = tensor(identity(4), destroy(N))
a.dag()*a

In [ ]:
#El .full sirve para ver todo completo
a.dag()*a*di2p2.full()

In [ ]:
tensor(identity(4), jmat(j,'+'))

## Hagamos una prueba haber si estas son las dimensiones correctas:

In [68]:
N=4
j=3/2
m=-j
wc=1
wa=1
g=0.5

a = destroy(N)

a.dag()

jz=jmat(j,'z')

jmin=jmat(j,'-')

jmax=jmat(j,'+')

In [69]:
#Esta es la forma en como se arreglaba el hamiltoniano, lo que había que hacer era un rpoducto tensorial entre los operadores.
#Y arreglar la dimensionalidad del segundo término
htc=wc*tensor(a.dag(),a) + wa*tensor(jz,identity(4)) + g*(tensor(a.dag(),jmin) + tensor(a,jmax))
htc

Quantum object: dims = [[4, 4], [4, 4]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.5         0.          0.          0.          0.          0.8660254
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          1.5         0.          0.          0.          0.
   1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          1.5         0.          0.          0.
   0.          0.8660254   0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          1.5         0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.5         0.
   0.          0.          0.          1.22474487  0.          0.
   0.          0.          0. 

In [61]:
#Así es como encuentro los componentes del hamiltoniano en su forma matricial.
htc.matrix_element(di0p0.dag(),di0p0)

(1.5+0j)

## Por ahora estoy teniendo valores cercanos a los que debería. 
## Muy parecidos respecto a las posiciones, pero no son los valores:

In [62]:
#Elementos del hamiltoniano

a1=htc.matrix_element(di3p3.dag(),di3p3)
a2=htc.matrix_element(di3p3.dag(),di2p2)
a3=htc.matrix_element(di3p3.dag(),di1p1)
a4=htc.matrix_element(di3p3.dag(),di0p0)

b1=htc.matrix_element(di2p2.dag(),di3p3)
b2=htc.matrix_element(di2p2.dag(),di2p2)
b3=htc.matrix_element(di2p2.dag(),di1p1)
b4=htc.matrix_element(di2p2.dag(),di0p0)

c1=htc.matrix_element(di1p1.dag(),di3p3)
c2=htc.matrix_element(di1p1.dag(),di2p2)
c3=htc.matrix_element(di1p1.dag(),di1p1)
c4=htc.matrix_element(di1p1.dag(),di0p0)

d1=htc.matrix_element(di0p0.dag(),di3p3)
d2=htc.matrix_element(di0p0.dag(),di2p2)
d3=htc.matrix_element(di0p0.dag(),di1p1)
d4=htc.matrix_element(di0p0.dag(),di0p0)

In [64]:
h=np.array([[a1,a2,a3,a4],[b1,b2,b3,b4],[c1,c2,c3,c4],[d1,d2,d3,d4]])
h

array([[-1.5       +0.j,  1.5       +0.j,  0.        +0.j,
         0.        +0.j],
       [ 1.5       +0.j, -0.5       +0.j,  1.41421356+0.j,
         0.        +0.j],
       [ 0.        +0.j,  1.41421356+0.j,  0.5       +0.j,
         0.8660254 +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.8660254 +0.j,
         1.5       +0.j]])