# Vamos a encontrar los coeficientes de expansión

In [22]:
import numpy as np



In [23]:
# Ponemos la forma del hamiltonaino que tenemos

# Los valores que ellos utilizan

# wc = 1.25
# wa = 1.0
# g = 0.05

wc = 1
wa = 1
g = 0.5
J=3/2

l=np.array([[3-J, g*(6*J)**(1/2),0,0],[g*(6*J)**(1/2),2-(J-1),2*g*(2*J-1)**(1/2),0],[0,2*g*(2*J-1)**(1/2), 1-(J-2) ,g*(6*(J-1))**(1/2)],[0,0,g*(6*(J-1))**(1/2), -(J-3)]])

print(l)

[[1.5        1.5        0.         0.        ]
 [1.5        1.5        1.41421356 0.        ]
 [0.         1.41421356 1.5        0.8660254 ]
 [0.         0.         0.8660254  1.5       ]]


In [24]:
import numpy as np

# Definir una matriz (por ejemplo)
# matriz = np.array([[1, 2], [2, 4]])

# Encontrar los autovalores y autofunciones
autovalores, autofunciones = np.linalg.eig(l)

# Mostrar los autovalores y autofunciones
print("Autovalores:")
print(autovalores)
print("\nAutofunciones:")
print(autofunciones)

Autovalores:
[-0.65313746  3.65313746  0.89667665  2.10332335]

Autofunciones:
[[ 0.46982945  0.46982945  0.52845084 -0.52845084]
 [-0.67440493  0.67440493 -0.21255115 -0.21255115]
 [ 0.52845084  0.52845084 -0.46982945  0.46982945]
 [-0.21255115  0.21255115  0.67440493  0.67440493]]


# Esto me dio unos autovalores y unas autofunciones diferentes que la resolución anterior :C

In [25]:
import sympy as sp

# Definir una matriz (como símbolos)
# a, b, c, d = sp.symbols('a b c d')
matriz_sympy = sp.Matrix(l)

# Calcular autovalores y autovectores
autovalores_sympy = matriz_sympy.eigenvals()
autovectores_sympy = matriz_sympy.eigenvects()

# Mostrar los resultados
print("Autovalores (SymPy):")
print(autovalores_sympy)
print("\nAutovectores (SymPy):")
print(autovectores_sympy)

Autovalores (SymPy):
{-0.653137463407616: 1, 3.65313746340762: 1, 0.896676650815985: 1, 2.10332334918402: 1}

Autovectores (SymPy):
[(-0.653137463407616, 1, [Matrix([
[  0.46982945118518],
[-0.674404928506034],
[ 0.528450836690635],
[-0.212551152447526]])]), (3.65313746340762, 1, [Matrix([
[ -0.46982945118518],
[-0.674404928506034],
[-0.528450836690635],
[-0.212551152447526]])]), (0.896676650815985, 1, [Matrix([
[ 0.528450836690635],
[-0.212551152447526],
[ -0.46982945118518],
[ 0.674404928506034]])]), (2.10332334918402, 1, [Matrix([
[-0.528450836690635],
[-0.212551152447526],
[  0.46982945118518],
[ 0.674404928506034]])])]


# Entocontrar los coheficientes

In [26]:
import sympy
from sympy import symbols, I, exp, simplify

a=symbols('a')
b=symbols('b')
c=symbols('c')
d=symbols('d')

t=symbols('t',real=True)

e1=sp.exp(-0.65313746*I*t)
e2=sp.exp(3.65313746*I*t)
e3=sp.exp(0.89667665*I*t)
e4=sp.exp(2.10332335*I*t)

In [27]:
# Autovalores:
# [-0.65313746  3.65313746  0.89667665  2.10332335]

# Autofunciones:
# [[ 0.46982945  0.46982945  0.52845084 -0.52845084]
#  [-0.67440493  0.67440493 -0.21255115 -0.21255115]
#  [ 0.52845084  0.52845084 -0.46982945  0.46982945]
#  [-0.21255115  0.21255115  0.67440493  0.67440493]]

In [28]:
c1=a*0.46982945*e1+b*0.46982945*e2+c*0.52845084*e3-d*0.52845084*e4

c2=-a*0.67440493*e1+b*0.67440493*e2-c*0.21255115*e3-d*0.21255115*e4

c3=a*0.52845084*e1+b*0.52845084*e2 -c*0.46982945*e3+d*0.46982945*e4

c4=-a*0.21255115*e1+b*0.21255115*e2+c*0.67440493*e3+d*0.67440493*e4


Aplicando condiciones iniciales, se pueden hallar a, b, c y d



In [29]:
import sympy as sp

# Definir vwriwbles simbólicws
w, x, y, z = sp.symbols('w x y z')

# Definir lws ecuwciones

y1=w*0.46982945*1+x*0.46982945*1+y*0.52845084*1-z*0.52845084*1-((2)**(1/2))/3

y2=-w*0.67440493*1+x*0.67440493*1-y*0.21255115*1-z*0.21255115*1+0

y3=w*0.52845084*1+x*0.52845084*1 -y*0.46982945*1+z*0.46982945*1+0

y4=-w*0.21255115*1+x*0.21255115*1+y*0.67440493*1+z*0.67440493*1-((7)**(1/2))/3

# Resolver el sistemw de ecuwciones
solucion = sp.solve((y1,y2,y3,y4), (w,x, y,z))

print("Lw solución es:", solucion)

Lw solución es: {w: 0.0340272314465424, x: 0.408932219902948, y: 0.843883355223323, z: 0.345655127615246}


# Valores de a, b,c y d

In [30]:
a=0.0340272314465424
b=0.408932219902948
c=0.843883355223323
d=0.345655127615246

## Valores de los números

In [31]:
c1=a*0.46982945*e1+b*0.46982945*e2+c*0.52845084*e3-d*0.52845084*e4
c2=-a*0.67440493*e1+b*0.67440493*e2-c*0.21255115*e3-d*0.21255115*e4
c3=a*0.52845084*e1+b*0.52845084*e2 -c*0.46982945*e3+d*0.46982945*e4
c4=-a*0.21255115*e1+b*0.21255115*e2+c*0.67440493*e3+d*0.67440493*e4

c1c=sp.conjugate(c1)
c2c=sp.conjugate(c2)
c3c=sp.conjugate(c3)
c4c=sp.conjugate(c4)

# Matriz densidad

In [32]:
print(c1)

0.445950867929783*exp(0.89667665*I*t) - 0.182661742538584*exp(2.10332335*I*t) + 0.192128399964281*exp(3.65313746*I*t) + 0.0159869954355517*exp(-0.65313746*I*t)


In [33]:
print(c1c)

0.0159869954355517*exp(0.65313746*I*t) + 0.192128399964281*exp(-3.65313746*I*t) - 0.182661742538584*exp(-2.10332335*I*t) + 0.445950867929783*exp(-0.89667665*I*t)


In [34]:

print(sp.simplify(c1*c1c))

-0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045


Según mis cálculos más términos deberían salir (+2), por eso...

Creamole a este mk que esto está bien.



Vamos a hacer una prueba: vamos a hallar los valores de la traza para t=0


In [35]:
#Esto es para simplificar la multiplicación, note como en lugar de escribirlo de forma exponencial lo entrega en funciones de seno y coseno
#Primer elemento de matriz densidad
print(sp.simplify(c1*c1c))

-0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045


In [36]:
#22 elemento de matriz densidad
print(sp.simplify(c2*c2c))

0.0263561723277769*cos(1.2066467*t) - 0.0322913084901371*cos(1.54981411*t) - 0.0955625699119408*cos(2.75646081*t) - 0.012657543063709*cos(4.30627492*t) + 0.11415524913801


In [37]:
#33 elemento de matriz densidad
print(sp.simplify(c3*c3c))

-0.128776284987598*cos(1.2066467*t) + 0.0559301876771036*cos(1.54981411*t) - 0.165519228547635*cos(2.75646081*t) + 0.00777171965239449*cos(4.30627492*t) + 0.230593606205735


In [38]:
#44 elemento de matriz densidad
print(sp.simplify(c4*c4c))

0.265336437082906*cos(1.2066467*t) + 0.0322913084901371*cos(1.54981411*t) + 0.0955625699119408*cos(2.75646081*t) - 0.00125728825600057*cos(4.30627492*t) + 0.385844750548795


Aquí compruebo si la traza de la matriz densidad es 1:

In [39]:
#.subs(t, 0) sirve para evalular en la ecacuión antes del punto, el valor de t=0
#Aquí encontré la traza :3
print(sp.simplify(c4*c4c).subs(t, 0)+sp.simplify(c3*c3c).subs(t, 0)+sp.simplify(c2*c2c).subs(t, 0)+sp.simplify(c1*c1c).subs(t, 0))

1.00000000000000


Bien, si la traza de esa matriz densidad me dió uno estpy más que feliz. 
Pero es solo para un tiempo de cero segundos.
¿Cambia mucho cuando se toman más segundos? 

Recuerda que el valor máximo de coseno corresponde a cuando el angulo es cero, es decir, la prueba inicial era suficiente.

In [40]:
#.subs(t, 0) sirve para evalular en la ecacuión antes del punto, el valor de t=0
#Aquí encontré la traza :3
v=0.000001
print(sp.simplify(c4*c4c).subs(t, v)+sp.simplify(c3*c3c).subs(t, v)+sp.simplify(c2*c2c).subs(t, v)+sp.simplify(c1*c1c).subs(t, v))

1.00000000000000


No, igual se necesita menos que eso, porque el experimento se hace en un orden de los picosegundos. 

Expresión de la matriz de densidad:



In [44]:
import sympy as sp

# # Supongamos que c1, c2, c3, c4 son símbolos o expresiones simbólicas de SymPy
# c1, c2, c3, c4 = sp.symbols('c1 c2 c3 c4')

# # Supongamos que c1c, c2c, c3c, c4c son símbolos o expresiones simbólicas de SymPy
# c1c, c2c, c3c, c4c = sp.symbols('c1c c2c c3c c4c')

# Listas de símbolos o expresiones simbólicas (vectores)

lista_1 = [c1, c2, c3, c4]
lista_2 = [c1c, c2c, c3c, c4c]

vector_columna = lista_1
vector_fila = lista_2

# Crear una matriz para almacenar el resultado del producto
matriz_densidadtotal = []

# Realizar el producto de los vectores
for i in range(len(vector_columna)):
    fila = []
    for j in range(len(vector_fila)):
        producto = sp.simplify(vector_columna[i] * vector_fila[j])
        fila.append(producto)
    matriz_densidadtotal.append(fila)

# Imprimir la matriz resultante
for fila in matriz_densidadtotal:
    print(fila)
    
print(matriz_densidadtotal)

[-0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045, 0.0655274808242556*I*sin(1.2066467*t) + 0.0288937984811943*I*sin(1.54981411*t) - 0.152082422378388*I*sin(2.75646081*t) - 0.00881797601327395*I*sin(4.30627492*t) - 6.93889390390723e-18*cos(1.2066467*t) - 0.0775923923876654*cos(1.54981411*t) + 0.091542395379011*cos(2.75646081*t) - 0.0139500029913456, -1.38777878078145e-17*I*sin(1.2066467*t) + 0.0850322668547393*I*sin(1.54981411*t) - 0.178426391260075*I*sin(2.75646081*t) + 0.144843912985395*cos(1.2066467*t) - 0.00659143632466438*cos(1.54981411*t) + 0.0195066296179431*cos(2.75646081*t) + 0.00690959781583221*cos(4.30627492*t) - 0.164668704094506, -0.207912571248654*I*sin(1.2066467*t) + 0.0483402661019383*I*sin(1.54981411*t) + 0.0681766847483832*I*sin(2.75646081*t) - 0.00277914774776898*I*sin(4.30627492*t) + 0.034783717881117*cos(1.54981411*t) + 0.153153409549471*cos(2.7

# ejemplo: t=0

In [45]:
import sympy as sp

'''
Este código lo que hace es con el .subs(t, 0) es asignar un valor a t para cada elemento de la matriz densidad.
'''

# Listas de símbolos o expresiones simbólicas (vectores)
vector_columna = lista_1
vector_fila = lista_2

# Crear una matriz para almacenar el resultado del producto
matriz_densidadtotalcero = []

# Realizar el producto de los vectores
for i in range(len(vector_columna)):
    fila = []
    for j in range(len(vector_fila)):
        producto = sp.simplify(vector_columna[i].subs(t, 0) * vector_fila[j].subs(t, 0))
        fila.append(producto)
    matriz_densidadtotalcero.append(fila)

# Imprimir la matriz resultante
for fila in matriz_densidadtotalcero:
    print(fila)

print(1000*'¿')
print(matriz_densidadtotalcero)

[0.222222222222223, -5.39719282672548e-17, -1.30841038223648e-16, 0.415739709641550]
[-5.39719282672548e-17, 1.31083606839856e-32, 3.17778440823894e-32, -1.00972232039804e-16]
[-1.30841038223648e-16, 3.17778440823894e-32, 7.70371977754894e-32, -2.44781168581342e-16]
[0.415739709641550, -1.00972232039804e-16, -2.44781168581342e-16, 0.777777777777778]
¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿

In [46]:
print(np.trace(matriz_densidadtotalcero))


1.00000000000000


# Matrices reducidas.

# Matriz de densidad reducida de materia

In [51]:
# Función para imprimir la densidad_D
def imprimir_densidad_D(densidad_D):
    for fila in densidad_D:
        print(fila)

# Crear densidad_D 4x4 de ceros
densidad_D = [[0 for _ in range(4)] for _ in range(4)]

# Valores para la diagonal principal (puedes cambiar estos valores según tus preferencias)
valores_diagonal = [sp.simplify(c4*c4c), sp.simplify(c3*c3c), sp.simplify(c2*c2c), sp.simplify(c1*c1c)]

# Establecer los valores en la diagonal principal
for i in range(4):
    densidad_D[i][i] = valores_diagonal[i]

# Imprimir densidad_D final
print("densidad_D con valores en la diagonal principal:")
imprimir_densidad_D(densidad_D)

densidad_D con valores en la diagonal principal:
[0.265336437082906*cos(1.2066467*t) + 0.0322913084901371*cos(1.54981411*t) + 0.0955625699119408*cos(2.75646081*t) - 0.00125728825600057*cos(4.30627492*t) + 0.385844750548795, 0, 0, 0]
[0, -0.128776284987598*cos(1.2066467*t) + 0.0559301876771036*cos(1.54981411*t) - 0.165519228547635*cos(2.75646081*t) + 0.00777171965239449*cos(4.30627492*t) + 0.230593606205735, 0, 0]
[0, 0, 0.0263561723277769*cos(1.2066467*t) - 0.0322913084901371*cos(1.54981411*t) - 0.0955625699119408*cos(2.75646081*t) - 0.012657543063709*cos(4.30627492*t) + 0.11415524913801, 0]
[0, 0, 0, -0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045]


In [65]:
'Esta es la matriz de densidad reducida del componente de materia'
print(densidad_D)

[[0.265336437082906*cos(1.2066467*t) + 0.0322913084901371*cos(1.54981411*t) + 0.0955625699119408*cos(2.75646081*t) - 0.00125728825600057*cos(4.30627492*t) + 0.385844750548795, 0, 0, 0], [0, -0.128776284987598*cos(1.2066467*t) + 0.0559301876771036*cos(1.54981411*t) - 0.165519228547635*cos(2.75646081*t) + 0.00777171965239449*cos(4.30627492*t) + 0.230593606205735, 0, 0], [0, 0, 0.0263561723277769*cos(1.2066467*t) - 0.0322913084901371*cos(1.54981411*t) - 0.0955625699119408*cos(2.75646081*t) - 0.012657543063709*cos(4.30627492*t) + 0.11415524913801, 0], [0, 0, 0, -0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045]]


# Matriz de densidad reducida fotónica

In [66]:
# Función para imprimir la densidad_ph
def imprimir_densidad_ph(densidad_ph):
    for fila in densidad_ph:
        print(fila)

# Crear densidad_ph 4x4 de ceros
densidad_ph = [[0 for _ in range(4)] for _ in range(4)]

# Valores para la diagonal principal (puedes cambiar estos valores según tus preferencias)
valores_diagonal = [sp.simplify(c1*c1c), sp.simplify(c2*c2c), sp.simplify(c3*c3c), sp.simplify(c4*c4c)]

# Establecer los valores en la diagonal principal
for i in range(4):
    densidad_ph[i][i] = valores_diagonal[i]

# Imprimir densidad_ph final
print("densidad_ph con valores en la diagonal principal:")
imprimir_densidad_ph(densidad_ph)

densidad_ph con valores en la diagonal principal:
[-0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045, 0, 0, 0]
[0, 0.0263561723277769*cos(1.2066467*t) - 0.0322913084901371*cos(1.54981411*t) - 0.0955625699119408*cos(2.75646081*t) - 0.012657543063709*cos(4.30627492*t) + 0.11415524913801, 0, 0]
[0, 0, -0.128776284987598*cos(1.2066467*t) + 0.0559301876771036*cos(1.54981411*t) - 0.165519228547635*cos(2.75646081*t) + 0.00777171965239449*cos(4.30627492*t) + 0.230593606205735, 0]
[0, 0, 0, 0.265336437082906*cos(1.2066467*t) + 0.0322913084901371*cos(1.54981411*t) + 0.0955625699119408*cos(2.75646081*t) - 0.00125728825600057*cos(4.30627492*t) + 0.385844750548795]


In [67]:
print(densidad_ph)

[[-0.162916325245296*cos(1.2066467*t) - 0.0559301876771036*cos(1.54981411*t) + 0.165519228547635*cos(2.75646081*t) + 0.00614311170653763*cos(4.30627492*t) + 0.26940639489045, 0, 0, 0], [0, 0.0263561723277769*cos(1.2066467*t) - 0.0322913084901371*cos(1.54981411*t) - 0.0955625699119408*cos(2.75646081*t) - 0.012657543063709*cos(4.30627492*t) + 0.11415524913801, 0, 0], [0, 0, -0.128776284987598*cos(1.2066467*t) + 0.0559301876771036*cos(1.54981411*t) - 0.165519228547635*cos(2.75646081*t) + 0.00777171965239449*cos(4.30627492*t) + 0.230593606205735, 0], [0, 0, 0, 0.265336437082906*cos(1.2066467*t) + 0.0322913084901371*cos(1.54981411*t) + 0.0955625699119408*cos(2.75646081*t) - 0.00125728825600057*cos(4.30627492*t) + 0.385844750548795]]
